local:
  server:
    port: 8080

spring.data.mongodb.port: 0

smsClient:
  client: textbelt
  url: http://localhost:8089/text
  socketTimeout: 2000
  connectionRequestTimeout: 2000
  connectionTimeout: 3000
  connectionTotal: 5